apiVersion : apps/v1
kind : Deployment
metadata : 
  name : "flask-assignment"
  labels:
    app: flask-app-deploy   

spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: flaskapp
  template: 
    metadata:
      labels:
        app: flaskapp
    spec:
      containers :
        - name : "myc1"
          image : "ritik8823/flask-assignment"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flaskservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: flaskapp
  externalIPs:
  - 192.168.0.10
    
